import { useEffect, useState } from 'react';
import { Copy, Trash2, Plus, AlertCircle, Loader2, X, Check } from 'lucide-react';
import { supabase } from '../../lib/supabase';

const ApiKey = () => {
    const [loading, setLoading] = useState(true);
    const [keys, setKeys] = useState<any[]>([]);
    const [showCreateModal, setShowCreateModal] = useState(false);
    const [newKeyName, setNewKeyName] = useState('');
    const [creating, setCreating] = useState(false);
    // State to show the newly created key just once
    const [createdKeyData, setCreatedKeyData] = useState<any>(null);

    const fetchKeys = async () => {
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            const { data, error } = await supabase
                .from('api_keys')
                .select('*')
                .eq('user_id', user.id)
                .order('created_at', { ascending: false });

            if (data) setKeys(data);
            if (error) console.error(error);
        } catch (error) {
            console.error(error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchKeys();
    }, []);

    const handleCreateKey = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!newKeyName.trim()) return;
        setCreating(true);

        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) throw new Error('Not authenticated');

            // Generate a random mock key (in real app, backend or DB function should do this securely)
            // But here we rely on the DB default value if possible, or generate on client.
            // Our Schema says: default 'sk-' || ... so we just insert name and user_id.

            const { data, error } = await supabase
                .from('api_keys')
                .insert({
                    user_id: user.id,
                    name: newKeyName,
                    // key_value will be auto-generated by DB default
                })
                .select()
                .single();

            if (error) throw error;

            // Success
            setCreatedKeyData(data);
            setNewKeyName('');
            fetchKeys(); // Refresh list
        } catch (error: any) {
            alert('创建失败: ' + error.message);
        } finally {
            setCreating(false);
        }
    };

    const handleDeleteKey = async (id: string) => {
        if (!confirm('确定要删除这个密钥吗？删除后无法恢复，使用此密钥的请求将失效。')) return;

        try {
            const { error } = await supabase
                .from('api_keys')
                .delete()
                .eq('id', id);

            if (error) throw error;
            fetchKeys(); // Refresh
        } catch (error: any) {
            alert('删除失败: ' + error.message);
        }
    };

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        // Could add toast here
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-64">
                <Loader2 className="animate-spin text-orange-500" size={32} />
            </div>
        );
    }

    return (
        <div className="space-y-6 relative">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-2xl font-bold text-white">API Keys</h2>
                    <p className="text-gray-400 mt-1">管理您用于调用API的密钥，请妥善保管。</p>
                </div>
                <button
                    onClick={() => setShowCreateModal(true)}
                    className="px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg flex items-center gap-2 transition-colors"
                >
                    <Plus size={18} />
                    <span>新建 Key</span>
                </button>
            </div>

            <div className="bg-[#141414] rounded-2xl border border-white/10 overflow-hidden">
                <table className="w-full text-left">
                    <thead>
                        <tr className="bg-white/5 border-b border-white/10">
                            <th className="p-4 text-sm font-medium text-gray-400">名称</th>
                            <th className="p-4 text-sm font-medium text-gray-400">Key</th>
                            <th className="p-4 text-sm font-medium text-gray-400">创建时间</th>
                            <th className="p-4 text-sm font-medium text-gray-400 text-right">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {keys.map((key) => (
                            <tr key={key.id} className="border-b border-white/5 hover:bg-white/5 transition-colors group">
                                <td className="p-4 text-white font-medium">{key.name}</td>
                                <td className="p-4 text-gray-300 font-mono flex items-center gap-2">
                                    <span>{key.key_value ? (key.key_value.slice(0, 8) + '••••••••' + key.key_value.slice(-4)) : 'sk-••••••••'}</span>
                                    <button
                                        onClick={() => copyToClipboard(key.key_value)}
                                        className="text-gray-500 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity"
                                    >
                                        <Copy size={14} />
                                    </button>
                                </td>
                                <td className="p-4 text-gray-400 text-sm">
                                    {new Date(key.created_at).toLocaleDateString()}
                                </td>
                                <td className="p-4 text-right">
                                    <button
                                        onClick={() => handleDeleteKey(key.id)}
                                        className="p-2 text-gray-500 hover:text-red-500 transition-colors"
                                    >
                                        <Trash2 size={16} />
                                    </button>
                                </td>
                            </tr>
                        ))}
                        {keys.length === 0 && (
                            <tr>
                                <td colSpan={5} className="p-12 text-center text-gray-500">
                                    暂无 API Key，请点击右上角新建。
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

            <div className="bg-orange-500/10 border border-orange-500/20 rounded-xl p-4 flex gap-3 text-orange-200 text-sm">
                <AlertCircle size={20} className="shrink-0 text-orange-500" />
                <p>
                    为了您的账户安全，API Key 仅在创建时显示一次完整内容，请务必立即复制并安全保存。
                    如发生泄露，请立即删除旧 Key 并生成新的 Key。
                </p>
            </div>

            {/* Create Key Modal */}
            {showCreateModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                    <div className="bg-[#1a1a1a] border border-white/10 rounded-xl max-w-md w-full p-6 shadow-2xl">
                        {!createdKeyData ? (
                            <form onSubmit={handleCreateKey}>
                                <div className="flex justify-between items-center mb-6">
                                    <h3 className="text-xl font-bold text-white">新建 API Key</h3>
                                    <button
                                        type="button"
                                        onClick={() => setShowCreateModal(false)}
                                        className="text-gray-400 hover:text-white"
                                    >
                                        <X size={20} />
                                    </button>
                                </div>
                                <div className="mb-6">
                                    <label className="block text-sm font-medium text-gray-400 mb-2">
                                        密钥名称
                                    </label>
                                    <input
                                        type="text"
                                        value={newKeyName}
                                        onChange={(e) => setNewKeyName(e.target.value)}
                                        placeholder="例如：Test Project"
                                        className="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-orange-500 transition-colors"
                                        autoFocus
                                    />
                                </div>
                                <div className="flex justify-end gap-3">
                                    <button
                                        type="button"
                                        onClick={() => setShowCreateModal(false)}
                                        className="px-4 py-2 text-gray-400 hover:text-white transition-colors"
                                    >
                                        取消
                                    </button>
                                    <button
                                        type="submit"
                                        disabled={creating || !newKeyName.trim()}
                                        className="px-4 py-2 bg-orange-500 hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg flex items-center gap-2 transition-colors"
                                    >
                                        {creating && <Loader2 size={16} className="animate-spin" />}
                                        创建
                                    </button>
                                </div>
                            </form>
                        ) : (
                            <div>
                                <div className="flex justify-between items-center mb-6">
                                    <div className="flex items-center gap-3">
                                        <div className="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center text-green-500">
                                            <Check size={20} />
                                        </div>
                                        <h3 className="text-xl font-bold text-white">创建成功</h3>
                                    </div>
                                    <button
                                        type="button"
                                        onClick={() => {
                                            setCreatedKeyData(null);
                                            setShowCreateModal(false);
                                        }}
                                        className="text-gray-400 hover:text-white"
                                    >
                                        <X size={20} />
                                    </button>
                                </div>
                                <p className="text-gray-400 mb-4 text-sm">
                                    这是您新的 API Key，请立即复制并保存。<br />
                                    <span className="text-orange-500">关闭此窗口后将无法再次查看完整密钥。</span>
                                </p>
                                <div className="bg-black/50 border border-white/10 rounded-lg p-4 mb-6 flex items-center justify-between group">
                                    <code className="text-green-400 font-mono text-sm break-all">
                                        {createdKeyData.key_value}
                                    </code>
                                    <button
                                        type="button"
                                        onClick={() => copyToClipboard(createdKeyData.key_value)}
                                        className="p-2 text-gray-500 hover:text-white transition-colors"
                                    >
                                        <Copy size={16} />
                                    </button>
                                </div>
                                <button
                                    onClick={() => {
                                        setCreatedKeyData(null);
                                        setShowCreateModal(false);
                                    }}
                                    className="w-full py-3 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors"
                                >
                                    我已保存，关闭窗口
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
};

export default ApiKey;
